import { createElement } from "lwc";
import AgentforcePromptModalGenerator from "c/agentforcePromptModalGenerator";
import invokePromptAndUserModelsGenAi from "@salesforce/apex/PackageVisualizerCtrl.invokePromptAndUserModelsGenAi";

jest.mock(
  "@salesforce/apex/PackageVisualizerCtrl.invokePromptAndUserModelsGenAi",
  () => ({
    default: jest.fn()
  }),
  { virtual: true }
);

describe("c-agentforce-prompt-modal-generator", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-agentforce-prompt-modal-generator", {
      is: AgentforcePromptModalGenerator
    });
    element.content = {
      userPrompt: "Write a prompt",
      systemPrompt: "You are helpful"
    };
    invokePromptAndUserModelsGenAi.mockResolvedValue("Generated prompt");

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
