import {
  PACKAGE_VISUALIZER_AGENT_SCRIPT,
  PACKAGE_VISUALIZER_AGENT_SCRIPT_COACHING_EVIDENCE,
  PACKAGE_VISUALIZER_AGENT_SCRIPT_MANIFEST,
  PACKAGE_VISUALIZER_AGENT_SCRIPT_PUBLIC_CHAT_SUMMARY,
  PACKAGE_VISUALIZER_AGENT_SCRIPT_SHA256,
  PACKAGE_VISUALIZER_AGENT_SCRIPT_SOURCE_VERSION
} from "./packageVisualizerAgentScriptGenerated.js";

export const AGENT_SCRIPTS = [
  {
    id: "package-visualizer-agent",
    label: "Package Visualizer Agent (Employee)",
    sourceVersion: PACKAGE_VISUALIZER_AGENT_SCRIPT_SOURCE_VERSION,
    body: PACKAGE_VISUALIZER_AGENT_SCRIPT,
    scriptHash: PACKAGE_VISUALIZER_AGENT_SCRIPT_SHA256,
    manifest: PACKAGE_VISUALIZER_AGENT_SCRIPT_MANIFEST,
    coachingEvidence: PACKAGE_VISUALIZER_AGENT_SCRIPT_COACHING_EVIDENCE,
    publicChatSummary: PACKAGE_VISUALIZER_AGENT_SCRIPT_PUBLIC_CHAT_SUMMARY
  }
];
