import { createElement } from "lwc";
import CampaignTile from "c/campaignTile";

describe("c-campaign-tile", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-campaign-tile", {
      is: CampaignTile
    });
    element.campaign = {
      Campaign: {
        Id: "701000000000001AAA",
        Name: "Test Campaign",
        StartDate: "2026-05-22",
        Type: "Email"
      },
      Status: "Sent"
    };

    // Act
    document.body.appendChild(element);

    // Assert
    const tile = element.shadowRoot.querySelector("lightning-tile");
    expect(tile.href).toBe("/lightning/r/Campaign/701000000000001AAA/view");
  });
});
