/**
 * @description {{ClassDescription}}
 * @author {{Author}}
 * @date {{Date}}
 */
public with sharing class {{ClassName}} {

    /**
     * @description {{MethodDescription}}
     * @param {{paramName}} {{ParamDescription}}
     * @return {{ReturnDescription}}
     */
    public {{ReturnType}} {{methodName}}({{ParamType}} {{paramName}}) {
        // TODO: Implement logic
        return null;
    }
}
